export const ReceivingActionTypes = {
  RECEIVING_FETCH_SUCCESS: 'RECEIVING_FETCH_SUCCESS',
  RECEIVING_ADD_TRACKING_TO_LIST: 'RECEIVING_ADD_TRACKING_TO_LIST',
  RECEIVING_REMOVE_TRACKING_IN_LIST: 'RECEIVING_REMOVE_TRACKING_IN_LIST',
  RECEIVING_EMPTY_LIST: 'RECEIVING_EMPTY_LIST'
}