export const InventoryActionTypes = {
  INVENTORY_FETCH_SUCCESS: 'INVENTORY_FETCH_SUCCESS',
  INVENTORY_UPDATE_RECV_ITEMS: 'INVENTORY_UPDATE_RECV_ITEMS',
  INVENTORY_MATCH_ITEMS: 'INVENTORY_MATCH_ITEMS'
}