export const ItemActionTypes = {
  ITEM_FETCH_SUCCESS: 'ITEM_FETCH_SUCCESS',
  ITEM_ADD_TO_LIST: 'ITEM_ADD_TO_LIST',
  ITEM_REMOVE_IN_LIST: 'ITEM_REMOVE_IN_LIST',
  ITEM_EMPTY_LIST: 'ITEM_EMPTY_LIST',
  COPY_ITEM_TO_EDIT: 'COPY_ITEM_TO_EDIT',
  COPY_ITEMS_TO_LIST: 'COPY_ITEMS_TO_LIST'
}