export const OrderActionTypes = {
  ORDER_FETCH_SUCCESS: 'ORDER_FETCH_SUCCESS',
  UPDATE_ITEM_IN_ORDER: 'UPDATE_ITEM_IN_ORDER',
  UPDATE_PURCHASING_IN_ORDER: 'UPDATE_PURCHASING_IN_ORDER',
  UPDATE_CUSTOMER_IN_ORDER: 'UPDATE_CUSTOMER_IN_ORDER',
  SELECT_PRODUCT_TO_ORDER_ITEM: 'SELECT_PRODUCT_TO_ORDER_ITEM',
  SET_ITEM_TEMP_TO_EDIT: 'SET_ITEM_TEMP_TO_EDIT',
  SET_PURC_ITEM_TAB_ACTIVE: 'SET_PURC_ITEM_TAB_ACTIVE'
}