export const OrderActionTypes = {
  ORDER_FETCH_SUCCESS: 'ORDER_FETCH_SUCCESS',
  COPY_ORDER_TO_EDIT: 'COPY_ORDER_TO_EDIT',
  UPDATE_ITEM_IN_ORDER: 'UPDATE_ITEM_IN_ORDER',
  UPDATE_PURCHASING_IN_ORDER: 'UPDATE_PURCHASING_IN_ORDER'
}